title: CHIJ Our Lady of Good Counsel
url: https://chijourladyofgoodcounsel.moe.edu.sg
favicon: /images/favicon-16x16.png
colors:
  primary-color: "#4a90e2"
  secondary-color: "#4a90e2"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: The Convent of Our Lady of Good Counsel, as the school was
  originally called, was established in the 1960 in a single building block with
  its main school gate at Cooling Close, Serangoon Gardens.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1qu38ykr1wc9w.amplifyapp.com
prod: https://master.d1qu38ykr1wc9w.amplifyapp.com
shareicon: /images/CHIJOLGC shareicon.jpg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
